from ast_nodes import *

class LLVMGenerator:
    def __init__(self, ast, symtab):
        self.ast = ast
        self.symtab = symtab
        self.code = []
        self.reg_count = 0
        self.label_count = 0
        self.local_vars = {} # maps var name to LLVM register or ptr

    def new_reg(self):
        self.reg_count += 1
        return f"%{self.reg_count}"

    def new_label(self):
        self.label_count += 1
        return f"L{self.label_count}"

    def emit(self, instruction):
        self.code.append(instruction)

    def map_type(self, c_type):
        if c_type == 'int': return 'i32'
        elif c_type == 'float': return 'float'
        elif c_type == 'double': return 'double'
        return 'i32' # default

    def generate(self):
        self.emit("; LLVM IR Generated by Custom Compiler")
        self.emit("declare i32 @printf(i8*, ...)")
        self.visit(self.ast)
        return "\n".join(self.code)

    def visit(self, node):
        if node is None:
            return None
        method_name = f'visit_{type(node).__name__}'
        visitor = getattr(self, method_name, self.generic_visit)
        return visitor(node)

    def generic_visit(self, node):
        return None

    def visit_Program(self, node):
        for decl in node.declarations:
            self.visit(decl)

    def visit_FunctionDecl(self, node):
        ret_type = self.map_type(node.return_type)
        params = []
        for p_type, p_name in node.params:
            params.append(f"{self.map_type(p_type)} %{p_name}_arg")
        
        param_str = ", ".join(params)
        self.emit(f"define {ret_type} @{node.name}({param_str}) {{")
        self.emit("entry:")
        self.reg_count = 0
        self.local_vars = {}
        
        # Allocate local variables for parameters
        for p_type, p_name in node.params:
            llvm_type = self.map_type(p_type)
            ptr = self.new_reg()
            self.emit(f"  {ptr} = alloca {llvm_type}")
            self.emit(f"  store {llvm_type} %{p_name}_arg, {llvm_type}* {ptr}")
            self.local_vars[p_name] = {'ptr': ptr, 'type': llvm_type}
            
        self.visit(node.body)
        
        # Add default return if void/missing
        if ret_type == 'i32':
            self.emit("  ret i32 0")
        elif ret_type == 'float':
            self.emit("  ret float 0.0")
        elif ret_type == 'double':
            self.emit("  ret double 0.0")
        self.emit("}\n")

    def visit_Block(self, node):
        for stmt in node.statements:
            self.visit(stmt)

    def visit_VarDecl(self, node):
        llvm_type = self.map_type(node.var_type)
        ptr = self.new_reg()
        self.emit(f"  {ptr} = alloca {llvm_type}")
        self.local_vars[node.name] = {'ptr': ptr, 'type': llvm_type}
        
        if node.init_expr:
            val, val_type = self.visit(node.init_expr)
            self.emit(f"  store {llvm_type} {val}, {llvm_type}* {ptr}")

    def visit_ArrayDecl(self, node):
        llvm_type = self.map_type(node.var_type)
        ptr = self.new_reg()
        self.emit(f"  {ptr} = alloca {llvm_type}, i32 {node.size}")
        self.local_vars[node.name] = {'ptr': ptr, 'type': llvm_type, 'is_array': True, 'size': node.size}

    def visit_AssignStmt(self, node):
        val, val_type = self.visit(node.expr)
        var_info = self.local_vars[node.name]
        self.emit(f"  store {var_info['type']} {val}, {var_info['type']}* {var_info['ptr']}")

    def visit_ArrayAssignStmt(self, node):
        idx_val, _ = self.visit(node.index_expr)
        val, val_type = self.visit(node.expr)
        var_info = self.local_vars[node.name]
        
        ptr = self.new_reg()
        self.emit(f"  {ptr} = getelementptr {var_info['type']}, {var_info['type']}* {var_info['ptr']}, i32 {idx_val}")
        self.emit(f"  store {var_info['type']} {val}, {var_info['type']}* {ptr}")

    def visit_ReturnStmt(self, node):
        if node.expr:
            val, val_type = self.visit(node.expr)
            self.emit(f"  ret {val_type} {val}")
        else:
            self.emit("  ret void")

    def visit_IfStmt(self, node):
        cond_val, _ = self.visit(node.condition)
        # Convert condition to i1
        cond_i1 = self.new_reg()
        self.emit(f"  {cond_i1} = icmp ne i32 {cond_val}, 0")
        
        then_label = self.new_label()
        else_label = self.new_label()
        end_label = self.new_label()
        
        if node.else_branch:
            self.emit(f"  br i1 {cond_i1}, label %{then_label}, label %{else_label}")
        else:
            self.emit(f"  br i1 {cond_i1}, label %{then_label}, label %{end_label}")
            
        self.emit(f"{then_label}:")
        self.visit(node.then_branch)
        self.emit(f"  br label %{end_label}")
        
        if node.else_branch:
            self.emit(f"{else_label}:")
            self.visit(node.else_branch)
            self.emit(f"  br label %{end_label}")
            
        self.emit(f"{end_label}:")

    def visit_WhileStmt(self, node):
        cond_label = self.new_label()
        body_label = self.new_label()
        end_label = self.new_label()
        
        self.emit(f"  br label %{cond_label}")
        self.emit(f"{cond_label}:")
        
        cond_val, _ = self.visit(node.condition)
        cond_i1 = self.new_reg()
        self.emit(f"  {cond_i1} = icmp ne i32 {cond_val}, 0")
        self.emit(f"  br i1 {cond_i1}, label %{body_label}, label %{end_label}")
        
        self.emit(f"{body_label}:")
        self.visit(node.body)
        self.emit(f"  br label %{cond_label}")
        
        self.emit(f"{end_label}:")

    def visit_ForStmt(self, node):
        self.visit(node.init)
        
        cond_label = self.new_label()
        body_label = self.new_label()
        end_label = self.new_label()
        
        self.emit(f"  br label %{cond_label}")
        self.emit(f"{cond_label}:")
        
        cond_val, _ = self.visit(node.condition)
        cond_i1 = self.new_reg()
        self.emit(f"  {cond_i1} = icmp ne i32 {cond_val}, 0")
        self.emit(f"  br i1 {cond_i1}, label %{body_label}, label %{end_label}")
        
        self.emit(f"{body_label}:")
        self.visit(node.body)
        self.visit(node.increment)
        self.emit(f"  br label %{cond_label}")
        
        self.emit(f"{end_label}:")

    def visit_BinOp(self, node):
        left_val, left_type = self.visit(node.left)
        right_val, right_type = self.visit(node.right)
        res = self.new_reg()
        
        if left_type == 'i32':
            if node.op == '+': self.emit(f"  {res} = add i32 {left_val}, {right_val}")
            elif node.op == '-': self.emit(f"  {res} = sub i32 {left_val}, {right_val}")
            elif node.op == '*': self.emit(f"  {res} = mul i32 {left_val}, {right_val}")
            elif node.op == '/': self.emit(f"  {res} = sdiv i32 {left_val}, {right_val}")
            elif node.op == '%': self.emit(f"  {res} = srem i32 {left_val}, {right_val}")
            elif node.op in ['==', '!=', '<', '<=', '>', '>=']:
                icmp_op = {'==': 'eq', '!=': 'ne', '<': 'slt', '<=': 'sle', '>': 'sgt', '>=': 'sge'}[node.op]
                i1_res = self.new_reg()
                self.emit(f"  {i1_res} = icmp {icmp_op} i32 {left_val}, {right_val}")
                self.emit(f"  {res} = zext i1 {i1_res} to i32")
        return res, left_type

    def visit_UnaryOp(self, node):
        val, val_type = self.visit(node.expr)
        res = self.new_reg()
        if val_type == 'i32':
            if node.op == '-':
                self.emit(f"  {res} = sub i32 0, {val}")
            elif node.op == '!':
                i1_res = self.new_reg()
                self.emit(f"  {i1_res} = icmp eq i32 {val}, 0")
                self.emit(f"  {res} = zext i1 {i1_res} to i32")
        return res, val_type

    def visit_Var(self, node):
        var_info = self.local_vars[node.name]
        res = self.new_reg()
        self.emit(f"  {res} = load {var_info['type']}, {var_info['type']}* {var_info['ptr']}")
        return res, var_info['type']

    def visit_ArrayAccess(self, node):
        idx_val, _ = self.visit(node.index_expr)
        var_info = self.local_vars[node.name]
        ptr = self.new_reg()
        self.emit(f"  {ptr} = getelementptr {var_info['type']}, {var_info['type']}* {var_info['ptr']}, i32 {idx_val}")
        res = self.new_reg()
        self.emit(f"  {res} = load {var_info['type']}, {var_info['type']}* {ptr}")
        return res, var_info['type']

    def visit_Number(self, node):
        if node.val_type == 'float':
            return f"{node.value:.6e}", 'float'
        return str(node.value), 'i32'

    def visit_FuncCall(self, node):
        args_vals = []
        args_types = []
        for arg in node.args:
            val, v_type = self.visit(arg)
            args_vals.append(val)
            args_types.append(v_type)
            
        arg_strs = [f"{t} {v}" for t, v in zip(args_types, args_vals)]
        arg_str = ", ".join(arg_strs)
        
        res = self.new_reg()
        self.emit(f"  {res} = call i32 @{node.name}({arg_str})") # assuming i32 return for simplicity
        return res, 'i32'
