; LLVM IR Generated by Custom Compiler
declare i32 @printf(i8*, ...)
define i32 @main() {
entry:
  %1 = alloca i32
  store i32 10, i32* %1
  %2 = alloca i32
  store i32 8, i32* %2
  %3 = alloca i32
  %4 = load i32, i32* %1
  %5 = load i32, i32* %2
  %6 = mul i32 %4, %5
  store i32 %6, i32* %3
  %7 = load i32, i32* %3
  ret i32 %7
  ret i32 0
}
