; LLVM IR Generated by Custom Compiler
declare i32 @printf(i8*, ...)
define i32 @arithmetic() {
entry:
  %1 = alloca i32
  store i32 10, i32* %1
  %2 = alloca i32
  store i32 8, i32* %2
  %3 = alloca i32
  %4 = load i32, i32* %1
  %5 = load i32, i32* %2
  %6 = mul i32 %4, %5
  store i32 %6, i32* %3
  %7 = load i32, i32* %3
  ret i32 %7
  ret i32 0
}

define i32 @loops() {
entry:
  %1 = alloca i32
  store i32 0, i32* %1
  %2 = alloca i32
  store i32 0, i32* %2
  br label %L1
L1:
  %3 = load i32, i32* %2
  %5 = icmp slt i32 %3, 10
  %4 = zext i1 %5 to i32
  %6 = icmp ne i32 %4, 0
  br i1 %6, label %L2, label %L3
L2:
  %7 = load i32, i32* %1
  %8 = load i32, i32* %2
  %9 = add i32 %7, %8
  store i32 %9, i32* %1
  %10 = load i32, i32* %2
  %11 = add i32 %10, 1
  store i32 %11, i32* %2
  br label %L1
L3:
  %12 = alloca i32
  store i32 0, i32* %12
  br label %L4
L4:
  %13 = load i32, i32* %12
  %15 = icmp slt i32 %13, 5
  %14 = zext i1 %15 to i32
  %16 = icmp ne i32 %14, 0
  br i1 %16, label %L5, label %L6
L5:
  %17 = load i32, i32* %1
  %18 = load i32, i32* %12
  %19 = add i32 %17, %18
  store i32 %19, i32* %1
  %20 = load i32, i32* %12
  %21 = add i32 %20, 1
  store i32 %21, i32* %12
  br label %L4
L6:
  %22 = load i32, i32* %1
  ret i32 %22
  ret i32 0
}

define i32 @add(i32 %x_arg, i32 %y_arg) {
entry:
  %1 = alloca i32
  store i32 %x_arg, i32* %1
  %2 = alloca i32
  store i32 %y_arg, i32* %2
  %3 = load i32, i32* %1
  %4 = load i32, i32* %2
  %5 = add i32 %3, %4
  ret i32 %5
  ret i32 0
}

define i32 @main() {
entry:
  %1 = alloca i32, i32 5
  %2 = getelementptr i32, i32* %1, i32 0
  store i32 10, i32* %2
  %3 = getelementptr i32, i32* %1, i32 1
  store i32 20, i32* %3
  %4 = alloca i32
  %5 = getelementptr i32, i32* %1, i32 0
  %6 = load i32, i32* %5
  %7 = getelementptr i32, i32* %1, i32 1
  %8 = load i32, i32* %7
  %9 = call i32 @add(i32 %6, i32 %8)
  store i32 %9, i32* %4
  %10 = load i32, i32* %4
  %11 = call i32 @arithmetic()
  %12 = add i32 %10, %11
  %13 = call i32 @loops()
  %14 = add i32 %12, %13
  ret i32 %14
  ret i32 0
}
