; LLVM IR Generated by Custom Compiler
declare i32 @printf(i8*, ...)
define i32 @add(i32 %x_arg, i32 %y_arg) {
entry:
  %1 = alloca i32
  store i32 %x_arg, i32* %1
  %2 = alloca i32
  store i32 %y_arg, i32* %2
  %3 = load i32, i32* %1
  %4 = load i32, i32* %2
  %5 = add i32 %3, %4
  ret i32 %5
  ret i32 0
}

define i32 @main() {
entry:
  %1 = alloca i32, i32 5
  %2 = getelementptr i32, i32* %1, i32 0
  store i32 10, i32* %2
  %3 = getelementptr i32, i32* %1, i32 1
  store i32 20, i32* %3
  %4 = alloca i32
  %5 = getelementptr i32, i32* %1, i32 0
  %6 = load i32, i32* %5
  %7 = getelementptr i32, i32* %1, i32 1
  %8 = load i32, i32* %7
  %9 = call i32 @add(i32 %6, i32 %8)
  store i32 %9, i32* %4
  %10 = load i32, i32* %4
  ret i32 %10
  ret i32 0
}
