; LLVM IR Generated by Custom Compiler
declare i32 @printf(i8*, ...)
define i32 @main() {
entry:
  %1 = alloca i32
  store i32 0, i32* %1
  %2 = alloca i32
  store i32 0, i32* %2
  br label %L1
L1:
  %3 = load i32, i32* %2
  %5 = icmp slt i32 %3, 10
  %4 = zext i1 %5 to i32
  %6 = icmp ne i32 %4, 0
  br i1 %6, label %L2, label %L3
L2:
  %7 = load i32, i32* %1
  %8 = load i32, i32* %2
  %9 = add i32 %7, %8
  store i32 %9, i32* %1
  %10 = load i32, i32* %2
  %11 = add i32 %10, 1
  store i32 %11, i32* %2
  br label %L1
L3:
  %12 = alloca i32
  store i32 0, i32* %12
  br label %L4
L4:
  %13 = load i32, i32* %12
  %15 = icmp slt i32 %13, 5
  %14 = zext i1 %15 to i32
  %16 = icmp ne i32 %14, 0
  br i1 %16, label %L5, label %L6
L5:
  %17 = load i32, i32* %1
  %18 = load i32, i32* %12
  %19 = add i32 %17, %18
  store i32 %19, i32* %1
  %20 = load i32, i32* %12
  %21 = add i32 %20, 1
  store i32 %21, i32* %12
  br label %L4
L6:
  %22 = load i32, i32* %1
  ret i32 %22
  ret i32 0
}
